from .begin import Begin
from .end import End
from .format_disk import FormatDisk
from .format_partitions import FormatPartitions
from .generate_fstab import GenerateFstab
from .bootstrap_arch_linux import BootstrapArchLinux
from .load_keymap import LoadKeymap
from .mount_partitions import MountPartitions
from .partition_disk import PartitionDisk
from .process_disk import ProcessDisk
from .process_system import ProcessSystem
from .select_disk import SelectDisk
from .select_keymap import SelectKeymap
from .select_locales import SelectLocales
from .select_main_locale import SelectMainLocale
from .select_pacman_mirrors import SelectPacmanMirrors
from .select_time_zone import SelectTimeZone
from .synchronize_ntp import SynchronizeNtp
from .unmount_partitions import UnmountPartitions
from .update_time_zone import UpdateTimeZone
