# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  deploy-docs:
    docker:
      - image: cimg/python:3.10-node
    steps:
      - checkout
      - run:
          name: "Install Poetry"
          command: "pip install poetry"
      - run:
          name: "Install Netlify CLI"
          command: "npm --prefix=./netlify-cli install --dev"
      - run:
          name: "Install dependencies"
          command: "poetry install --extras=docs"
      - run:
          name: "Generate documents"
          command: "make docs"
      - run:
          name: "Deploy to Netlify"
          command: "npm --prefix=./netlify-cli exec -- netlify deploy --prod"
  deploy-test-pypi:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: "Install Poetry"
          command: "pip install poetry"
      - run:
          name: "Install poetry-dynamic-versioning"
          command: "poetry self add poetry-dynamic-versioning"
      - run:
          name: "Install dependencies"
          command: "poetry install"
      - run:
          name: "Register test-pypi"
          command: "poetry config repositories.test-pypi https://test.pypi.org/legacy/"
      - run:
          name: "Register API token"
          command: "poetry config pypi-token.test-pypi $TEST_PYPI_TOKEN"
      - run:
          name: "Deploy to TestPyPI"
          command: "poetry publish --build --repository=test-pypi"
  install-sh:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Find a loopback device"
          command: "losetup --find"
  run-tests:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: "Install Poetry"
          command: "pip install poetry"
      - run:
          name: "Install dependencies"
          command: "poetry install --extras=test"
      - run:
          name: "Run tests"
          command: "make test"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  deploy-docs-workflow:
    jobs:
      - deploy-docs
  deploy-test-pypi-workflow:
    jobs:
      - deploy-test-pypi:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
  install-sh-workflow:
    jobs:
      - install-sh
  run-tests-workflow:
    jobs:
      - run-tests
