from .begin import Begin
from .end import End
from .format_disk import FormatDisk
from .format_partitions import FormatPartitions
from .generate_fstab import GenerateFstab
from .bootstrap_arch_linux import BootstrapArchLinux
from .mount_partitions import MountPartitions
from .partition_disk import PartitionDisk
from .select_disk import SelectDisk
from .select_pacman_mirrors import SelectPacmanMirrors
from .select_time_zone import SelectTimeZone
from .synchronize_ntp import SynchronizeNtp
from .unmount_partitions import UnmountPartitions
from .update_time_zone import UpdateTimeZone
