#!/usr/bin/env bash

# Branch name like "main"
branch_name="$(git branch | grep '*' | sed 's/^* //')"

# Exit if rebasing
if [ "$branch_name" = '(no branch)' ]; then
    exit 0
fi

if git status --short | grep -q '^M  CHANGELOG.rst$'; then
    :
else
    echo 'The commit MUST include modified CHANGELOG.rst.'
    exit 1
fi
